/**
 * levelData.js — GENERATED by tools/generateLevels.js — do not edit by hand.
 *
 * The built-in "main levels", stored as an internal module (no runtime
 * fetches). Each entry is a full level definition: metadata, song info,
 * theme colours and the object list, consumed by LevelRuntime.
 */
export const MAIN_LEVELS = [
 {
  "id": "level1",
  "name": "NEON RUNNER",
  "difficulty": "Easy",
  "bpm": 150,
  "speed": 10,
  "length": 420,
  "track": "runner",
  "theme": {
   "bg1": [
    0.02,
    0.004,
    0.055
   ],
   "bg2": [
    0.09,
    0.03,
    0.22
   ],
   "accent": [
    0,
    0.94,
    1
   ],
   "accent2": [
    1,
    0.18,
    0.65
   ],
   "ground": [
    0.05,
    0.02,
    0.13
   ],
   "block": [
    0.13,
    0.07,
    0.3
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 40,
    "y": 0
   },
   {
    "t": "spike",
    "x": 52,
    "y": 0
   },
   {
    "t": "spike",
    "x": 64,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 76,
    "y": 0
   },
   {
    "t": "block",
    "x": 88,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "coin",
    "x": 89,
    "y": 2.8
   },
   {
    "t": "spike",
    "x": 100,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 112,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "block",
    "x": 116,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 126,
    "y": 0
   },
   {
    "t": "spike",
    "x": 140,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "pad",
    "x": 158,
    "y": 0
   },
   {
    "t": "platform",
    "x": 161,
    "y": 3,
    "w": 8
   },
   {
    "t": "spike",
    "x": 162,
    "y": 0,
    "n": 6,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 178,
    "y": 0
   },
   {
    "t": "spike",
    "x": 190,
    "y": 0
   },
   {
    "t": "spike",
    "x": 198,
    "y": 0
   },
   {
    "t": "block",
    "x": 210,
    "y": 0,
    "w": 4,
    "h": 1
   },
   {
    "t": "spike",
    "x": 216,
    "y": 0
   },
   {
    "t": "spike",
    "x": 230,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 246,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 247,
    "y": 1.7
   },
   {
    "t": "pad",
    "x": 267,
    "y": 0
   },
   {
    "t": "block",
    "x": 271,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "coin",
    "x": 271,
    "y": 3.9
   },
   {
    "t": "spike",
    "x": 290,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 302,
    "y": 0
   },
   {
    "t": "block",
    "x": 312,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "block",
    "x": 316,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 326,
    "y": 0
   },
   {
    "t": "spike",
    "x": 336,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "coin",
    "x": 352,
    "y": 2.6
   },
   {
    "t": "spike",
    "x": 358,
    "y": 0
   },
   {
    "t": "spike",
    "x": 368,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 380,
    "y": 0
   },
   {
    "t": "spike",
    "x": 392,
    "y": 0
   }
  ],
  "stars": 1,
  "song": {
   "name": "Neon Runner",
   "artist": "NEOVOLT OST"
  }
 },
 {
  "id": "level2",
  "name": "VOLTAGE",
  "difficulty": "Normal",
  "bpm": 156,
  "speed": 10.4,
  "length": 500,
  "track": "voltage",
  "theme": {
   "bg1": [
    0,
    0.03,
    0.03
   ],
   "bg2": [
    0.01,
    0.1,
    0.09
   ],
   "accent": [
    0.3,
    1,
    0.5
   ],
   "accent2": [
    1,
    0.55,
    0.15
   ],
   "ground": [
    0.02,
    0.07,
    0.05
   ],
   "block": [
    0.05,
    0.16,
    0.1
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 36,
    "y": 0
   },
   {
    "t": "spike",
    "x": 46,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 56,
    "y": 0
   },
   {
    "t": "spike",
    "x": 64,
    "y": 0
   },
   {
    "t": "saw",
    "x": 77,
    "y": 1,
    "r": 1
   },
   {
    "t": "block",
    "x": 90,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "spike",
    "x": 94,
    "y": 0
   },
   {
    "t": "spike",
    "x": 104,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 116,
    "y": 0,
    "n": 12,
    "flip": 1
   },
   {
    "t": "platform",
    "x": 115,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 120,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 125,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "coin",
    "x": 120,
    "y": 3.9
   },
   {
    "t": "saw",
    "x": 145,
    "y": 1,
    "r": 1
   },
   {
    "t": "pad",
    "x": 158,
    "y": 0
   },
   {
    "t": "platform",
    "x": 162,
    "y": 2,
    "w": 6
   },
   {
    "t": "spike",
    "x": 163,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 173,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 190,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 204,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 205,
    "y": 1.7
   },
   {
    "t": "spike",
    "x": 220,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 230,
    "y": 0
   },
   {
    "t": "spike",
    "x": 238,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 254,
    "y": 0,
    "w": 3,
    "h": 1
   },
   {
    "t": "block",
    "x": 259,
    "y": 0,
    "w": 12,
    "h": 2
   },
   {
    "t": "spike",
    "x": 263,
    "y": 2
   },
   {
    "t": "coin",
    "x": 264,
    "y": 4.2
   },
   {
    "t": "saw",
    "x": 275,
    "y": 1,
    "r": 1
   },
   {
    "t": "saw",
    "x": 292,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 302,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 316,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 324,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 339,
    "y": 0.9,
    "r": 1
   },
   {
    "t": "saw",
    "x": 344,
    "y": 0.9,
    "r": 1
   },
   {
    "t": "saw",
    "x": 349,
    "y": 0.9,
    "r": 1
   },
   {
    "t": "platform",
    "x": 336,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 341,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 346,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "spike",
    "x": 365,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 366,
    "y": 1.7
   },
   {
    "t": "spike",
    "x": 378,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 379,
    "y": 1.7
   },
   {
    "t": "pad",
    "x": 395,
    "y": 0
   },
   {
    "t": "block",
    "x": 398,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "coin",
    "x": 398,
    "y": 4.5
   },
   {
    "t": "spike",
    "x": 415,
    "y": 0
   },
   {
    "t": "spike",
    "x": 423,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 433,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 445,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 455,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 463,
    "y": 0
   }
  ],
  "stars": 2,
  "song": {
   "name": "Voltage",
   "artist": "NEOVOLT OST"
  }
 },
 {
  "id": "level3",
  "name": "GRAVITY STORM",
  "difficulty": "Hard",
  "bpm": 160,
  "speed": 10.667,
  "length": 600,
  "track": "storm",
  "theme": {
   "bg1": [
    0.05,
    0,
    0.03
   ],
   "bg2": [
    0.16,
    0.02,
    0.1
   ],
   "accent": [
    1,
    0.25,
    0.35
   ],
   "accent2": [
    0.75,
    0.35,
    1
   ],
   "ground": [
    0.1,
    0.02,
    0.06
   ],
   "block": [
    0.22,
    0.05,
    0.12
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 32,
    "y": 0
   },
   {
    "t": "spike",
    "x": 40,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 48,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 60,
    "y": 1,
    "r": 1
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "fast",
    "x": 72,
    "y": 0
   },
   {
    "t": "spike",
    "x": 80,
    "y": 0
   },
   {
    "t": "spike",
    "x": 91,
    "y": 0
   },
   {
    "t": "spike",
    "x": 102,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 113,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "normal",
    "x": 126,
    "y": 0
   },
   {
    "t": "block",
    "x": 134,
    "y": 7,
    "w": 44,
    "h": 1
   },
   {
    "t": "portal",
    "kind": "gravity",
    "value": -1,
    "x": 137,
    "y": 0
   },
   {
    "t": "spike",
    "x": 146,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "spike",
    "x": 154,
    "y": 7,
    "n": 2,
    "flip": -1
   },
   {
    "t": "spike",
    "x": 162,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "coin",
    "x": 165,
    "y": 3.9
   },
   {
    "t": "spike",
    "x": 170,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "portal",
    "kind": "gravity",
    "value": 1,
    "x": 176,
    "y": 3.5
   },
   {
    "t": "spike",
    "x": 190,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 200,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 208,
    "y": 0,
    "n": 12,
    "flip": 1
   },
   {
    "t": "platform",
    "x": 207,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 212,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "platform",
    "x": 217,
    "y": 1.5,
    "w": 3
   },
   {
    "t": "spike",
    "x": 232,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 240,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 241,
    "y": 1.7
   },
   {
    "t": "pad",
    "x": 258,
    "y": 0
   },
   {
    "t": "spike",
    "x": 261,
    "y": 0,
    "n": 6,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 262,
    "y": 3.2
   },
   {
    "t": "coin",
    "x": 265,
    "y": 5.5
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "fast",
    "x": 285,
    "y": 0
   },
   {
    "t": "spike",
    "x": 292,
    "y": 0
   },
   {
    "t": "spike",
    "x": 303,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 315,
    "y": 0
   },
   {
    "t": "spike",
    "x": 326,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 340,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 350,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "slow",
    "x": 360,
    "y": 0
   },
   {
    "t": "spike",
    "x": 366,
    "y": 0
   },
   {
    "t": "spike",
    "x": 373,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 381,
    "y": 0
   },
   {
    "t": "spike",
    "x": 388,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 395,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "normal",
    "x": 402,
    "y": 0
   },
   {
    "t": "block",
    "x": 408,
    "y": 7,
    "w": 50,
    "h": 1
   },
   {
    "t": "portal",
    "kind": "gravity",
    "value": -1,
    "x": 411,
    "y": 0
   },
   {
    "t": "spike",
    "x": 420,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "spike",
    "x": 428,
    "y": 7,
    "n": 2,
    "flip": -1
   },
   {
    "t": "spike",
    "x": 438,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "coin",
    "x": 443,
    "y": 3.9
   },
   {
    "t": "spike",
    "x": 448,
    "y": 7,
    "n": 1,
    "flip": -1
   },
   {
    "t": "portal",
    "kind": "gravity",
    "value": 1,
    "x": 458,
    "y": 3.5
   },
   {
    "t": "spike",
    "x": 470,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 482,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 490,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 500,
    "y": 0,
    "n": 4,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 501,
    "y": 1.7
   },
   {
    "t": "pad",
    "x": 515,
    "y": 0
   },
   {
    "t": "block",
    "x": 518,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "spike",
    "x": 535,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 547,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 557,
    "y": 0
   },
   {
    "t": "spike",
    "x": 568,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 578,
    "y": 0
   }
  ],
  "stars": 3,
  "song": {
   "name": "Gravity Storm",
   "artist": "NEOVOLT OST"
  }
 },
 {
  "id": "level4",
  "name": "SKY DRIVE",
  "difficulty": "Normal",
  "stars": 2,
  "song": {
   "name": "Voltage (Flight Mix)",
   "artist": "NEOVOLT OST"
  },
  "bpm": 144,
  "speed": 9.6,
  "length": 400,
  "track": "voltage",
  "theme": {
   "bg1": [
    0,
    0.02,
    0.07
   ],
   "bg2": [
    0.02,
    0.09,
    0.2
   ],
   "accent": [
    0.25,
    0.75,
    1
   ],
   "accent2": [
    1,
    0.75,
    0.15
   ],
   "ground": [
    0.02,
    0.05,
    0.12
   ],
   "block": [
    0.07,
    0.13,
    0.28
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 36,
    "y": 0
   },
   {
    "t": "spike",
    "x": 48,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 60,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "coin",
    "x": 61,
    "y": 2.7
   },
   {
    "t": "spike",
    "x": 72,
    "y": 0
   },
   {
    "t": "spike",
    "x": 86,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 100,
    "y": 0
   },
   {
    "t": "block",
    "x": 112,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "block",
    "x": 116,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 126,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "ship",
    "x": 138,
    "y": 0
   },
   {
    "t": "block",
    "x": 136,
    "y": 8,
    "w": 140,
    "h": 1
   },
   {
    "t": "block",
    "x": 152,
    "y": 0,
    "w": 2,
    "h": 3
   },
   {
    "t": "block",
    "x": 166,
    "y": 5,
    "w": 2,
    "h": 3
   },
   {
    "t": "block",
    "x": 180,
    "y": 0,
    "w": 2,
    "h": 3
   },
   {
    "t": "block",
    "x": 194,
    "y": 5,
    "w": 2,
    "h": 3
   },
   {
    "t": "saw",
    "x": 208,
    "y": 4,
    "r": 1
   },
   {
    "t": "coin",
    "x": 208,
    "y": 0.7
   },
   {
    "t": "block",
    "x": 222,
    "y": 0,
    "w": 2,
    "h": 3
   },
   {
    "t": "block",
    "x": 236,
    "y": 5,
    "w": 2,
    "h": 3
   },
   {
    "t": "block",
    "x": 250,
    "y": 0,
    "w": 2,
    "h": 3
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 266,
    "y": 0
   },
   {
    "t": "spike",
    "x": 288,
    "y": 0
   },
   {
    "t": "spike",
    "x": 300,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 314,
    "y": 0
   },
   {
    "t": "coin",
    "x": 320,
    "y": 2.6
   },
   {
    "t": "spike",
    "x": 328,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 342,
    "y": 0
   },
   {
    "t": "spike",
    "x": 354,
    "y": 0,
    "n": 2,
    "flip": 1
   }
  ]
 },
 {
  "id": "level5",
  "name": "AFTERBURN",
  "difficulty": "Hard",
  "stars": 4,
  "song": {
   "name": "Gravity Storm (Afterburn Cut)",
   "artist": "NEOVOLT OST"
  },
  "bpm": 160,
  "speed": 10.667,
  "length": 560,
  "track": "storm",
  "theme": {
   "bg1": [
    0.06,
    0.01,
    0
   ],
   "bg2": [
    0.18,
    0.06,
    0.01
   ],
   "accent": [
    1,
    0.55,
    0.1
   ],
   "accent2": [
    1,
    0.2,
    0.3
   ],
   "ground": [
    0.1,
    0.04,
    0.01
   ],
   "block": [
    0.24,
    0.1,
    0.04
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 36,
    "y": 0
   },
   {
    "t": "spike",
    "x": 46,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 58,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 72,
    "y": 1,
    "r": 1
   },
   {
    "t": "pad",
    "x": 84,
    "y": 0
   },
   {
    "t": "block",
    "x": 88,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "coin",
    "x": 87,
    "y": 4.2
   },
   {
    "t": "spike",
    "x": 100,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 112,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "ship",
    "x": 124,
    "y": 0
   },
   {
    "t": "block",
    "x": 122,
    "y": 8,
    "w": 158,
    "h": 1
   },
   {
    "t": "block",
    "x": 136,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 150,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 164,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 178,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "saw",
    "x": 190,
    "y": 4,
    "r": 0.9
   },
   {
    "t": "block",
    "x": 202,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 216,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 230,
    "y": 3,
    "w": 3,
    "h": 2
   },
   {
    "t": "coin",
    "x": 231,
    "y": 6
   },
   {
    "t": "saw",
    "x": 244,
    "y": 2,
    "r": 0.8
   },
   {
    "t": "saw",
    "x": 244,
    "y": 6,
    "r": 0.8
   },
   {
    "t": "block",
    "x": 258,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 270,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 284,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "fast",
    "x": 296,
    "y": 0
   },
   {
    "t": "spike",
    "x": 304,
    "y": 0
   },
   {
    "t": "spike",
    "x": 315,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 327,
    "y": 0
   },
   {
    "t": "spike",
    "x": 339,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 352,
    "y": 1,
    "r": 1
   },
   {
    "t": "portal",
    "kind": "speed",
    "value": "normal",
    "x": 364,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "ship",
    "x": 376,
    "y": 0
   },
   {
    "t": "block",
    "x": 374,
    "y": 8,
    "w": 110,
    "h": 1
   },
   {
    "t": "block",
    "x": 388,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 400,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 412,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 424,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "saw",
    "x": 436,
    "y": 4,
    "r": 1
   },
   {
    "t": "coin",
    "x": 436,
    "y": 1.2
   },
   {
    "t": "block",
    "x": 448,
    "y": 3,
    "w": 2,
    "h": 2
   },
   {
    "t": "block",
    "x": 462,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 474,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 488,
    "y": 0
   },
   {
    "t": "spike",
    "x": 500,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 512,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "saw",
    "x": 526,
    "y": 1,
    "r": 1
   },
   {
    "t": "spike",
    "x": 538,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 548,
    "y": 0
   }
  ]
 },
 {
  "id": "level6",
  "name": "LOW ORBIT",
  "difficulty": "Normal",
  "stars": 4,
  "song": {
   "name": "Voltage (Orbital Mix)",
   "artist": "NEOVOLT OST"
  },
  "bpm": 152,
  "speed": 10.133,
  "length": 480,
  "track": "voltage",
  "theme": {
   "bg1": [
    0.03,
    0,
    0.08
   ],
   "bg2": [
    0.12,
    0.03,
    0.24
   ],
   "accent": [
    1,
    0.6,
    0.15
   ],
   "accent2": [
    0.65,
    0.4,
    1
   ],
   "ground": [
    0.07,
    0.02,
    0.16
   ],
   "block": [
    0.17,
    0.08,
    0.34
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 40,
    "y": 0
   },
   {
    "t": "spike",
    "x": 52,
    "y": 0
   },
   {
    "t": "spike",
    "x": 64,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 78,
    "y": 0
   },
   {
    "t": "block",
    "x": 90,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "spike",
    "x": 100,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "ufo",
    "x": 112,
    "y": 0
   },
   {
    "t": "block",
    "x": 116,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 128,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 140,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 152,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 164,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 176,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 188,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 200,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 212,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 132,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "spike",
    "x": 133,
    "y": 0
   },
   {
    "t": "coin",
    "x": 140,
    "y": 3.4
   },
   {
    "t": "block",
    "x": 150,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "block",
    "x": 151,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "saw",
    "x": 168,
    "y": 3.4,
    "r": 0.8
   },
   {
    "t": "block",
    "x": 182,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "block",
    "x": 198,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "spike",
    "x": 199,
    "y": 2
   },
   {
    "t": "block",
    "x": 214,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 224,
    "y": 0
   },
   {
    "t": "spike",
    "x": 238,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 252,
    "y": 0
   },
   {
    "t": "block",
    "x": 264,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 274,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "ufo",
    "x": 286,
    "y": 0
   },
   {
    "t": "block",
    "x": 290,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 302,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 314,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 326,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 338,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 350,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 362,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 374,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 386,
    "y": 7,
    "w": 6,
    "h": 1
   },
   {
    "t": "block",
    "x": 296,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "block",
    "x": 308,
    "y": 5,
    "w": 1,
    "h": 2
   },
   {
    "t": "coin",
    "x": 312,
    "y": 2.6
   },
   {
    "t": "block",
    "x": 320,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "spike",
    "x": 321,
    "y": 0
   },
   {
    "t": "saw",
    "x": 334,
    "y": 3.6,
    "r": 0.9
   },
   {
    "t": "block",
    "x": 346,
    "y": 5,
    "w": 1,
    "h": 2
   },
   {
    "t": "block",
    "x": 347,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "block",
    "x": 360,
    "y": 0,
    "w": 1,
    "h": 3
   },
   {
    "t": "saw",
    "x": 372,
    "y": 3.2,
    "r": 0.8
   },
   {
    "t": "block",
    "x": 384,
    "y": 0,
    "w": 1,
    "h": 2
   },
   {
    "t": "spike",
    "x": 385,
    "y": 2
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 396,
    "y": 0
   },
   {
    "t": "spike",
    "x": 410,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "coin",
    "x": 424,
    "y": 2.6
   },
   {
    "t": "spike",
    "x": 430,
    "y": 0
   },
   {
    "t": "spike",
    "x": 444,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 458,
    "y": 0
   }
  ]
 },
 {
  "id": "level7",
  "name": "WAVELENGTH",
  "difficulty": "Hard",
  "stars": 5,
  "song": {
   "name": "Neon Runner (Waveform Mix)",
   "artist": "NEOVOLT OST"
  },
  "bpm": 158,
  "speed": 10.533,
  "length": 490,
  "track": "runner",
  "theme": {
   "bg1": [
    0,
    0.03,
    0.08
   ],
   "bg2": [
    0.01,
    0.1,
    0.22
   ],
   "accent": [
    0.25,
    0.75,
    1
   ],
   "accent2": [
    0,
    0.94,
    1
   ],
   "ground": [
    0.01,
    0.06,
    0.14
   ],
   "block": [
    0.05,
    0.14,
    0.3
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 40,
    "y": 0
   },
   {
    "t": "spike",
    "x": 52,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 66,
    "y": 0
   },
   {
    "t": "spike",
    "x": 80,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "wave",
    "x": 94,
    "y": 0
   },
   {
    "t": "block",
    "x": 98,
    "y": 8,
    "w": 24,
    "h": 1
   },
   {
    "t": "block",
    "x": 126,
    "y": 8,
    "w": 24,
    "h": 1
   },
   {
    "t": "block",
    "x": 154,
    "y": 8,
    "w": 24,
    "h": 1
   },
   {
    "t": "block",
    "x": 182,
    "y": 8,
    "w": 24,
    "h": 1
   },
   {
    "t": "block",
    "x": 112,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 128,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "coin",
    "x": 138,
    "y": 4.2
   },
   {
    "t": "block",
    "x": 144,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 160,
    "y": 4,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 176,
    "y": 0,
    "w": 2,
    "h": 3
   },
   {
    "t": "saw",
    "x": 192,
    "y": 4,
    "r": 0.9
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 206,
    "y": 0
   },
   {
    "t": "spike",
    "x": 220,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "ring",
    "x": 221,
    "y": 1.7
   },
   {
    "t": "block",
    "x": 236,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "spike",
    "x": 246,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "wave",
    "x": 258,
    "y": 0
   },
   {
    "t": "block",
    "x": 262,
    "y": 7,
    "w": 22,
    "h": 1
   },
   {
    "t": "block",
    "x": 288,
    "y": 7,
    "w": 22,
    "h": 1
   },
   {
    "t": "block",
    "x": 314,
    "y": 7,
    "w": 22,
    "h": 1
   },
   {
    "t": "block",
    "x": 340,
    "y": 7,
    "w": 22,
    "h": 1
   },
   {
    "t": "block",
    "x": 366,
    "y": 7,
    "w": 22,
    "h": 1
   },
   {
    "t": "block",
    "x": 274,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "block",
    "x": 288,
    "y": 3.5,
    "w": 2,
    "h": 3.5
   },
   {
    "t": "block",
    "x": 302,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "coin",
    "x": 310,
    "y": 4.6
   },
   {
    "t": "block",
    "x": 316,
    "y": 3.5,
    "w": 2,
    "h": 3.5
   },
   {
    "t": "block",
    "x": 330,
    "y": 0,
    "w": 2,
    "h": 4.5
   },
   {
    "t": "saw",
    "x": 344,
    "y": 3.4,
    "r": 0.8
   },
   {
    "t": "block",
    "x": 356,
    "y": 3.5,
    "w": 2,
    "h": 3.5
   },
   {
    "t": "block",
    "x": 370,
    "y": 0,
    "w": 2,
    "h": 4
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 384,
    "y": 0
   },
   {
    "t": "spike",
    "x": 398,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 412,
    "y": 0
   },
   {
    "t": "coin",
    "x": 426,
    "y": 2.6
   },
   {
    "t": "spike",
    "x": 432,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 452,
    "y": 0
   }
  ]
 },
 {
  "id": "level8",
  "name": "STEEL PULSE",
  "difficulty": "Hard",
  "stars": 5,
  "song": {
   "name": "Gravity Storm (Steel Mix)",
   "artist": "NEOVOLT OST"
  },
  "bpm": 154,
  "speed": 10.267,
  "length": 490,
  "track": "storm",
  "theme": {
   "bg1": [
    0.04,
    0.04,
    0.06
   ],
   "bg2": [
    0.12,
    0.13,
    0.18
   ],
   "accent": [
    1,
    0.85,
    0.3
   ],
   "accent2": [
    1,
    0.35,
    0.25
   ],
   "ground": [
    0.08,
    0.08,
    0.11
   ],
   "block": [
    0.18,
    0.19,
    0.26
   ]
  },
  "objects": [
   {
    "t": "spike",
    "x": 40,
    "y": 0
   },
   {
    "t": "spike",
    "x": 54,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 68,
    "y": 0
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "robot",
    "x": 82,
    "y": 0
   },
   {
    "t": "spike",
    "x": 96,
    "y": 0
   },
   {
    "t": "spike",
    "x": 108,
    "y": 0
   },
   {
    "t": "spike",
    "x": 120,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 134,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "coin",
    "x": 135,
    "y": 4
   },
   {
    "t": "spike",
    "x": 148,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 160,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 160,
    "y": 2,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 176,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "block",
    "x": 192,
    "y": 0,
    "w": 2,
    "h": 2.5
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 206,
    "y": 0
   },
   {
    "t": "block",
    "x": 220,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "block",
    "x": 224,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 234,
    "y": 0
   },
   {
    "t": "spike",
    "x": 248,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "robot",
    "x": 262,
    "y": 0
   },
   {
    "t": "block",
    "x": 276,
    "y": 0,
    "w": 2,
    "h": 1
   },
   {
    "t": "block",
    "x": 280,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 292,
    "y": 0
   },
   {
    "t": "block",
    "x": 304,
    "y": 0,
    "w": 2,
    "h": 2.5
   },
   {
    "t": "coin",
    "x": 305,
    "y": 4.6
   },
   {
    "t": "spike",
    "x": 318,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "block",
    "x": 334,
    "y": 0,
    "w": 2,
    "h": 2
   },
   {
    "t": "spike",
    "x": 334,
    "y": 2,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 350,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "block",
    "x": 362,
    "y": 0,
    "w": 3,
    "h": 2.5
   },
   {
    "t": "saw",
    "x": 363.5,
    "y": 4.6,
    "r": 0.8
   },
   {
    "t": "spike",
    "x": 380,
    "y": 0,
    "n": 3,
    "flip": 1
   },
   {
    "t": "portal",
    "kind": "mode",
    "value": "cube",
    "x": 396,
    "y": 0
   },
   {
    "t": "spike",
    "x": 410,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 424,
    "y": 0
   },
   {
    "t": "coin",
    "x": 438,
    "y": 2.6
   },
   {
    "t": "spike",
    "x": 444,
    "y": 0,
    "n": 2,
    "flip": 1
   },
   {
    "t": "spike",
    "x": 458,
    "y": 0,
    "n": 3,
    "flip": 1
   }
  ]
 }
];
